/**
 * Admin-only industry tags for posts — separate from public categories.
 * Not shown on the public nav today; stored for future filtering/search.
 *
 * New entries are upserted automatically via `ensureIndustries()` on admin load.
 */
export const ADMIN_INDUSTRY_LIST = [
  { slug: "agency", name: "Agency" },
  { slug: "media", name: "Media" },
  { slug: "saas", name: "SaaS" },
  { slug: "consumer", name: "Consumer" },
  { slug: "b2b", name: "B2B" },
  { slug: "b2c", name: "B2C" },
  { slug: "startup", name: "Startup" },
  { slug: "enterprise", name: "Enterprise" },
  { slug: "crypto", name: "Crypto" },
  { slug: "web3", name: "Web3" },
  { slug: "fintech", name: "Fintech" },
  { slug: "finance", name: "Finance" },
  { slug: "insurance", name: "Insurance" },
  { slug: "ai", name: "AI" },
  { slug: "developer-tools", name: "Developer Tools" },
  { slug: "design-tools", name: "Design Tools" },
  { slug: "productivity", name: "Productivity" },
  { slug: "marketplace", name: "Marketplace" },
  { slug: "ecommerce", name: "Ecommerce" },
  { slug: "retail", name: "Retail" },
  { slug: "fashion", name: "Fashion" },
  { slug: "beauty", name: "Beauty" },
  { slug: "food-beverage", name: "Food & Beverage" },
  { slug: "hospitality", name: "Hospitality" },
  { slug: "travel", name: "Travel" },
  { slug: "mobility", name: "Mobility" },
  { slug: "automotive", name: "Automotive" },
  { slug: "real-estate", name: "Real Estate" },
  { slug: "architecture", name: "Architecture" },
  { slug: "interior-design", name: "Interior Design" },
  { slug: "construction", name: "Construction" },
  { slug: "industrial", name: "Industrial" },
  { slug: "hardware", name: "Hardware" },
  { slug: "aerospace", name: "Aerospace" },
  { slug: "energy", name: "Energy" },
  { slug: "climate", name: "Climate" },
  { slug: "agriculture", name: "Agriculture" },
  { slug: "logistics", name: "Logistics" },
  { slug: "healthcare", name: "Healthcare" },
  { slug: "wellness", name: "Wellness & Fitness" },
  { slug: "education", name: "Education" },
  { slug: "hr", name: "HR" },
  { slug: "legal", name: "Legal" },
  { slug: "government", name: "Government" },
  { slug: "security", name: "Security" },
  { slug: "telecom", name: "Telecom" },
  { slug: "gaming", name: "Gaming" },
  { slug: "sports", name: "Sports" },
  { slug: "entertainment", name: "Entertainment" },
  { slug: "music", name: "Music" },
  { slug: "publishing", name: "Publishing" },
  { slug: "news", name: "News" },
  { slug: "social", name: "Social" },
  { slug: "creator", name: "Creator Economy" },
  { slug: "marketing", name: "Marketing" },
  { slug: "events", name: "Events" },
  { slug: "dating", name: "Dating" },
  { slug: "non-profit", name: "Non-Profit" },
  { slug: "portfolio", name: "Portfolio / Personal" },
  { slug: "other", name: "Other" },
] as const;

export type AdminIndustrySlug = (typeof ADMIN_INDUSTRY_LIST)[number]["slug"];
